// Build the review memo .docx with docx-js, following this skill's own gotcha list.
const fs = require('fs');
const path = require('path');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, ShadingType,
  HeadingLevel, PageNumber, Footer, Header, TableOfContents, AlignmentType, BorderStyle,
  ImageRun, PositionalTab, PositionalTabAlignment, PositionalTabLeader, PositionalTabRelativeTo, LevelFormat,
} = require('docx');

const DIR = __dirname;
const facts = JSON.parse(fs.readFileSync(path.join(DIR, 'facts.json'), 'utf8'));
const chart = fs.readFileSync(path.join(DIR, 'chart.png'));

const PAGE_W = 12240, PAGE_H = 15840, MARGIN = 1440;
const CONTENT_DXA = PAGE_W - MARGIN * 2; // 9360
const COLS = [700, 2300, 2260, 1000, 1300, 1800]; // must sum to CONTENT_DXA
if (COLS.reduce((a, b) => a + b, 0) !== CONTENT_DXA) throw new Error('column widths do not sum to table width');

const FONT = { ascii: 'Calibri', hAnsi: 'Calibri', eastAsia: 'Microsoft YaHei' };
const t = (text, opts = {}) => new TextRun(Object.assign({ text, font: FONT, size: 22 }, opts));
const p = (children, opts = {}) => new Paragraph(Object.assign({ children, spacing: { after: 120, line: 300 } }, opts));

const bullets = (arr) => arr.map((s) => new Paragraph({ children: [t(s)], bullet: { level: 0 }, spacing: { after: 80 } }));

function dotLeader(label, value) {
  // docx-js quirk: a TextRun given both `text` and `children` emits only `children` and
  // silently drops the text, so the positional tab gets its own run.
  return new Paragraph({
    children: [
      t(label),
      new TextRun({ font: FONT, size: 22, children: [new PositionalTab({ alignment: PositionalTabAlignment.RIGHT, relativeTo: PositionalTabRelativeTo.MARGIN, leader: PositionalTabLeader.DOT })] }),
      t(value, { bold: true }),
    ],
    spacing: { after: 80 },
  });
}

function cell(text, { head = false, width, align } = {}) {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    shading: head ? { type: ShadingType.CLEAR, color: 'auto', fill: 'DCE6F1' } : undefined,
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
    children: [new Paragraph({
      alignment: align,
      children: [t(String(text), { bold: head, size: 20 })],
      spacing: { after: 0, line: 260 },
    })],
  });
}

const header = new TableRow({
  tableHeader: true,
  children: ['轮次', 'Skill', '产物类型', '耗时/分', '日志 PASS 计数', 'demos 体积/B'].map((s, i) => cell(s, { head: true, width: COLS[i], align: AlignmentType.CENTER })),
});

const dataRows = facts.rows.map((r) => new TableRow({
  children: [
    cell(r.n, { width: COLS[0], align: AlignmentType.CENTER }),
    cell(r.skill, { width: COLS[1] }),
    cell(r.artifact, { width: COLS[2] }),
    cell(r.minutes == null ? '未记' : r.minutes, { width: COLS[3], align: AlignmentType.RIGHT }),
    cell(r.pass, { width: COLS[4], align: AlignmentType.RIGHT }),
    cell(r.bytes.toLocaleString('en-US'), { width: COLS[5], align: AlignmentType.RIGHT }),
  ],
}));

const table = new Table({
  columnWidths: COLS,
  width: { size: CONTENT_DXA, type: WidthType.DXA },
  rows: [header, ...dataRows],
});

const hr = () => new Paragraph({
  children: [], spacing: { after: 160 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'AAB7C4' } },
});

const doc = new Document({
  creator: 'Skill 演示场评审组',
  title: 'Skill 演示场 · 前 11 轮验证纪要',
  description: 'Generated by the docx skill during the 12th showcase round',
  styles: {
    default: { document: { run: { font: FONT, size: 22 } } },
    paragraphStyles: [
      { id: 'Title', name: 'Title', basedOn: 'Normal', quickFormat: true, run: { size: 44, bold: true, color: '1F3864', font: FONT }, paragraph: { spacing: { before: 240, after: 120 } } },
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 30, bold: true, color: '1F3864', font: FONT }, paragraph: { spacing: { before: 280, after: 140 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 25, bold: true, color: '2E5496', font: FONT }, paragraph: { spacing: { before: 200, after: 120 }, outlineLevel: 1 } },
    ],
  },
  numbering: {
    config: [
      { reference: 'review-bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '\u2022', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 420, hanging: 260 } } } }] },
    ],
  },
  features: { updateFields: true },
  sections: [{
    properties: { page: { size: { width: PAGE_W, height: PAGE_H }, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } },
    headers: { default: new Header({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [t('Skill 演示场 · 内部评审纪要', { size: 18, color: '808080' })], spacing: { after: 0 } })] }) },
    footers: {
      default: new Footer({
        children: [new Paragraph({
          alignment: AlignmentType.CENTER, spacing: { after: 0 },
          children: [t('第 ', { size: 18 }), t('', { size: 18, children: [PageNumber.CURRENT] }), t(' 页 / 共 ', { size: 18 }), t('', { size: 18, children: [PageNumber.TOTAL_PAGES] }), t(' 页', { size: 18 })],
        })],
      }),
    },
    children: [
      p([t('Skill 演示场 · 前 11 轮有趣技能验证纪要', { size: 44, bold: true, color: '1F3864' })], { style: 'Title' }),
      p([t('无人值守自动化流水线 · 内部评审用 · 数据源为本仓库 state/state.json 与各轮 output.log', { size: 21, color: '595959' })]),
      p([t(`生成时间：${facts.generated}    编制：第 12 轮（docx 技能自举）`, { size: 20, color: '595959' })]),
      hr(),
      p([t('目录', { size: 26, bold: true })], { heading: HeadingLevel.HEADING_1 }),
      new TableOfContents('目录', { hyperlink: true, headingStyleRange: '1-2' }),
      new Paragraph({ children: [t('（目录域已写入并在打开时请求刷新；无域缓存值时 Word 显示占位提示，属预期）', { italics: true, size: 19, color: '808080' })], pageBreakBefore: true }),

      p([t('1. 结论摘要', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1 }),
      p([t('11 轮全部产出「肉眼可见」的交付物并完成独立断言，11 个技能全部判为留用；单轮耗时中位数在 12 分钟附近，仅 build-game 一轮超出 15 分钟预算。全局副作用集中在早期来自扩展市场的 5 个技能安装，最近三轮已实现零安装复用本地技能包。')]),
      dotLeader('已验证技能数', `${facts.totals.tried}`),
      dotLeader('候选技能登记数（skills_seen）', `${facts.totals.seen}`),
      dotLeader('交付物合计体积（11 轮 demos）', `${facts.totals.demoBytes.toLocaleString('en-US')} B`),
      dotLeader('本轮全局技能安装数', '0'),
      dotLeader('耗时口径可核轮次', `${facts.totals.minutesKnown} / 11`),

      p([t('2. 逐轮台账', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1, pageBreakBefore: true }),
      p([t('「日志 PASS 计数」取自各轮 demos/<run>/output.log 中 PASS 字样的出现次数，是证据密度而非正确率；第 8 轮（sec-audit-cn）产物为分级审计报告，日志不使用 PASS/FAIL 记法，故计数为 0。', { size: 20, color: '595959' })]),
      table,

      p([t('2.1 耗时分布', { size: 25, bold: true, color: '2E5496' })], { heading: HeadingLevel.HEADING_2 }),
      p([t('橙色柱为超出 15 分钟预算的轮次；红色虚线为预算线。第 8 轮跨越宿主休眠，秒数未记（runs[].seconds = null）。')]),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new ImageRun({ type: 'png', data: chart, transformation: { width: 480, height: 213 }, altText: { title: '单轮耗时柱状图', description: '第 1-11 轮分钟数与 15 分钟预算线', name: 'rounds-duration' } })],
      }),
      p([t('图 1　前 11 轮单轮耗时（分钟）· 由 chart.html 经系统 Chrome 无头 CLI 出图后嵌入', { size: 19, italics: true, color: '595959' })], { alignment: AlignmentType.CENTER }),

      p([t('3. 交付物类型分布', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1, pageBreakBefore: true }),
      ...bullets([
        '网页类（自包含 HTML）3 轮：drafter 工程图纸、algorithmic-art 生成艺术、build-game 3D 游戏；',
        '二进制办公类 3 轮：pptx、xlsx，以及本份 docx —— 至此 Word/Excel/PPT 三形态齐备；',
        '图像与动效类 3 轮：GIF（48 帧循环）、真 PNG 截图、p5 画布下载图；',
        '数据与结论类 2 轮：SQLite FTS5 检索库、分级安全审计报告；',
        '纯文本类 1 轮：ASCII 终端看板 + Go 覆盖率页。',
      ]),

      p([t('4. 选题与验证纪律', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1 }),
      ...bullets([
        '去重契约：tried[] 命中即不可再选，skills_seen[] 中 unreachable/blocked 来源不再探测；',
        '安全闸门：执行前完整读 SKILL.md 与其引用的脚本，拒绝读取凭据、拒绝外发本地内容、写盘限制在实验目录内；',
        '验收范式：第 10 轮确立「golden + 不变量」双变异自证，第 11 轮确立「网络卫生断言须并收服务端访问日志」；',
        '产物判据一律现场取期望值，不写死默认值（第 11 轮纪律，本纪要的数字同样由 facts.cjs 现场实测）。',
      ]),

      p([t('5. 风险与处置', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1 }),
      p([
        t('交付物中约九成字节为单行内联的第三方库，且产物内无可机检来源，推送后无法自证上游版本；'),
        t('该缺陷由第 8 轮安全审计判为「高」，处置方式为在产物旁保留 integrity-manifest 并在下一轮补入 sha256 清单。'),
      ]),
      p([
        t('市场镜像技能包存在只搬 SKILL.md、丢 scripts 与 references 的情况，'),
        t('本轮同类风险已在第 6 轮真实发生。'),
      ]),

      p([t('6. 决议', { size: 30, bold: true, color: '1F3864' })], { heading: HeadingLevel.HEADING_1 }),
      ...bullets([
        '11 个技能全部留用，技能库不做裁剪；',
        '后续轮次优先复用 LAB/.skills 已有技能包，避免继续扩张全局技能目录；',
        '产物类型继续按 used_artifact_kinds 轮换，同一类型不超过约 3 次。',
      ]),
      p([t('附：复现口径　facts.cjs 读本仓库 state/state.json 与各 demos/<run>/output.log；chart.html 由系统 Chrome 无头 CLI 截图为 chart.png；build.cjs 生成 base.docx；comment.py 与手工 <w:ins>/<w:del> 补丁生成终稿；校验见 output.log。', { size: 19, color: '595959' })]),
    ],
  }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync(path.join(DIR, 'base.docx'), buf);
  console.log('base.docx %d bytes', buf.length);
});
